export const LOG_ON = 'LOG_ON';
export const LOG_OFF = 'LOG_OFF';
export const IS_FETCHING = 'IS_FETCHING_USER';
export const USER_FETCHING_SUCCESS = 'FETCHING_SUCCESS_UPDATE_USER';
export const PLANTS_FETCHING_SUCCESS = 'FETCHING_SUCCESS_UPDATE_PLANTS';
export const TOGGLE_MODAL = 'TOGGLE_MODAL';
export const PLANT_FORM_INFO = 'PLANT_FORM_INFO';
